-- This is a template for the content of a SQL file generated by Aster Development Environment.
-- This template should be edited to contain the SQL that will invoke your SQL-MR function.
SELECT *
FROM PeakPick2D(
      ON  (select scan, mslvl, rettime, mzarray, intensityarray
			 from christest.data_pt2441s1fp1a1_new
			 where mslvl = 1
			 limit 1)
);