-- This is a template for the content of a SQL file generated by Aster Development Environment.
-- This template should be edited to contain the SQL that will invoke your SQL-MR function.
SELECT *
FROM PeakPick3d(
      ON (SELECT * FROM peaks2d_100312 LIMIT 2000) 
      Partition by pkey
      order by scan
); 	